import { GameDefinition } from "./gameDefinition.js";

/**
 * In-memory lookup of GameDefinitions by id. The server wraps this (or reads
 * straight from Postgres) — the registry itself doesn't care whether a
 * definition came from a hardcoded seed or was generated by the AI game
 * generator, since both are just validated GameDefinition data.
 */
export class GameRegistry {
  private readonly definitions = new Map<string, GameDefinition>();

  register(definition: GameDefinition): void {
    this.definitions.set(definition.id, definition);
  }

  get(id: string): GameDefinition | undefined {
    return this.definitions.get(id);
  }

  list(): GameDefinition[] {
    return [...this.definitions.values()];
  }
}
